language: generic
sudo: required
services:
    - docker
before-install:
    - docker build -t ramesh/docker-react -f Dockerfile.dev .
script:
    - docker run -it -e CI=true ramesh/docker-react  npm run test --  --coverage