version: '3'
services: 
    web:
        ports: 
            - "3000:3000"
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true

    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command:  ["npm", "run","test"]
        